# Generated by Django 5.2.8 on 2025-12-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='variable_mappings',
            field=models.TextField(blank=True, help_text='JSON mapping of variables to values or recipient fields'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='recipient',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
