# Generated by Django 5.2.8 on 2025-12-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_campaign_variable_mappings_recipient_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='sending_current_email',
            field=models.CharField(blank=True, help_text='Currently processing email', max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sending_progress',
            field=models.IntegerField(default=0, help_text='Number of emails sent so far'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sending_total',
            field=models.IntegerField(default=0, help_text='Total number of emails to send'),
        ),
    ]
